[metadata]
name = tristan-detector
description = A Python based odin-control interface library to the Tristan detector
url = https://github.com/dls-controls/tristan-detector
author = Alan Greer
author_email = alan.greer@diamond.ac.uk
license = Apache License 2.0
# long_description = file: README.rst
# long_description_content_type = text/x-rst
classifiers =
    Development Status :: 3 - Alpha,
    Intended Audience :: Science/Research,
    Topic :: Scientific/Engineering,
    License :: OSI Approved :: Apache Software License
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9

keywords=
  Timepix3, Tristan, Detector, LATRD

[options]
packages = find:
package_dir =
    = src

python_requires >=3.7

install_requires =
    odin-data>=1.7.0
    # odin-control 1.2 has different entry-point
    odin-control>=1.3
    python-dateutil
    # numpy 1.22 requires python 3.8
    numpy<1.22
    # metawriter needs h5py
    h5py

[options.package_data]
    * = static/*, static/js/*, static/img/*, static/confex/*

[options.extras_require]
test =
  nose>=1.3
  coverage
  mock
  requests

[options.packages.find]
where = src
exclude =
  docs
  sandbox
  test*

[options.entry_points]
# Include a command line script
console_scripts =
   tristan_odin=odin.main:main
   tristan_simulator=tristan_detector.control.control_simulator:main


[nosetests]
verbosity=2
nocapture=1
detailed-errors=1
with-coverage=1
cover-package=tristan_detector
cover-erase=1

[flake8]
max-line-length = 100

[versioneer]
VCS = git
style = pep440
versionfile_source = src/tristan_detector/_version.py
versionfile_build = tristan_detector/_version.py
tag_prefix=
